#! /usr/bin/env zsh

# MIT License

# Copyright (c) 2019 Alexandros Kozak

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

(( $+EPOCHSECONDS )) || zmodload zsh/datetime

jumpstart_z() {
  local autojump_datafile=$1
  local now=$EPOCHSECONDS

  local lines=( ${(f)"$(< $autojump_datafile)"} )

  local line
  for line in $lines; do
    local weight_field=${line%[[:blank:]]*}
    local path_field=${line#*[[:blank:]]}

    print "$path_field|${weight_field%[[:punct:]]*}|$now"
  done
}

jumpstart_z "$@"

# vim: ts=2:sts=2:sw=2:et:
