#!/bin/sh

# MIT License

# Copyright (c) 2019 Alexandros Kozak

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

jumpstart_z() {
  for JZ_AWK_FLAVOR in mawk gawk original-awk nawk awk; do
	  command -v $JZ_AWK_FLAVOR > /dev/null 2>&1 && JZ_AWK=$JZ_AWK_FLAVOR && break
  done

  $JZ_AWK -F "\t" -v now="$(date +%s)" '
    { printf("%s|%0.f|%s\n", $2, $1, now) }
  ' < "$1"
}

jumpstart_z "$@"

# vim: ts=2:sts=2:sw=2:et:
